select jsonb_build_object(
 'counts',jsonb_build_object('lessons',(select count(*) from public.lessons),'modules',(select count(*) from public.course_modules),'cross_course_parents',(select count(*) from public.lessons l join public.course_modules m on m.id=l.module_id where l.course_id<>m.course_id)),
 'fingerprints',jsonb_build_object('lessons',(select md5(coalesce(jsonb_agg(to_jsonb(l) order by id)::text,'[]')) from public.lessons l),'modules',(select md5(coalesce(jsonb_agg(to_jsonb(m) order by id)::text,'[]')) from public.course_modules m)),
 'rls',(select jsonb_agg(jsonb_build_object('table',relname,'enabled',relrowsecurity)) from pg_class where oid in ('public.lessons'::regclass,'public.course_modules'::regclass)),
 'grants',jsonb_build_object('anon_lesson_id',has_column_privilege('anon','public.lessons','id','SELECT'),'auth_lesson_id',has_column_privilege('authenticated','public.lessons','id','SELECT'),'auth_blocks',has_column_privilege('authenticated','public.lessons','blocks','SELECT'),'auth_video',has_column_privilege('authenticated','public.lessons','video_url','SELECT'),'auth_legacy',has_column_privilege('authenticated','public.lessons','legacy_payload','SELECT'),'auth_lesson_write',has_table_privilege('authenticated','public.lessons','INSERT,UPDATE,DELETE,TRUNCATE'),'auth_module_write',has_table_privilege('authenticated','public.course_modules','INSERT,UPDATE,DELETE,TRUNCATE'),'service_read',has_table_privilege('service_role','public.lessons','SELECT')),
 'policies',(select jsonb_agg(jsonb_build_object('table',tablename,'name',policyname,'cmd',cmd,'type',permissive)) from pg_policies where schemaname='public' and tablename in ('lessons','course_modules')),
 'predicate',jsonb_build_object('definer',(select prosecdef from pg_proc where oid='public.can_current_user_read_course_outline(text,boolean)'::regprocedure),'anon_exec',has_function_privilege('anon','public.can_current_user_read_course_outline(text,boolean)','EXECUTE'),'auth_exec',has_function_privilege('authenticated','public.can_current_user_read_course_outline(text,boolean)','EXECUTE')),
 'inactive_profiles_with_active_enrollment',(select count(*) from public.profiles p join public.enrollments e on e.user_id=p.id where p.is_active=false and e.status in ('active','completed'))
) as verification;
