import { EmotionFamily } from "./types";

export const initialEmotionFamilies: EmotionFamily[] = [
  {
    id: "alegria",
    name: "Alegria",
    description: "Expansão, contentamento e vivacidade diante do que nutre.",
    colorToken: "#01C94D",
    nuances: [
      {
        id: "contentamento",
        familyId: "alegria",
        label: "Contentamento",
        description: "Uma paz serena e estável com o momento presente.",
        example: "Sentir-se em casa após um dia longo, sem pressa.",
        question: "Onde no corpo você percebe essa quietude?",
        synonyms: ["paz", "plenitude", "bem-estar", "satisfação tranquila"],
      },
      {
        id: "entusiasmo",
        familyId: "alegria",
        label: "Entusiasmo",
        description: "Vibração e impulso para realizar ou participar.",
        example: "O brilho ao iniciar um projeto ou encontrar alguém querido.",
        question: "Para onde se direciona a sua energia agora?",
        synonyms: ["ânimo", "excitação", "inspiração", "vigor"],
      },
      {
        id: "satisfacao",
        familyId: "alegria",
        label: "Satisfação",
        description: "Reconhecimento de que algo foi concluído ou nutrido.",
        example: "Terminar uma tarefa desafiadora e descansar.",
        question: "O que essa sensação diz sobre o seu esforço?",
        synonyms: ["realização", "contentamento", "completude"],
      },
    ],
  },
  {
    id: "tristeza",
    name: "Tristeza",
    description:
      "Recolhimento, elaboração de perdas e pedido interno de pausa.",
    colorToken: "#07614C",
    nuances: [
      {
        id: "desanimo",
        familyId: "tristeza",
        label: "Desânimo",
        description: "Sensação de falta de impulso ou energia vital baixa.",
        example: "Acordar sentindo o corpo pesado diante da rotina.",
        question: "Do que seu corpo está pedindo descanso?",
        synonyms: ["esgotamento", "apatia leve", "fadiga", "prostração"],
      },
      {
        id: "pesar",
        familyId: "tristeza",
        label: "Pesar",
        description: "Dor pelo que se foi ou pela impossibilidade de algo.",
        example: "Lembrar de uma fase que se encerrou.",
        question: "Qual aspecto dessa perda pede acolhimento?",
        synonyms: ["luto", "melancolia", "dor", "angústia sutil"],
      },
      {
        id: "saudade",
        familyId: "tristeza",
        label: "Saudade",
        description: "A presença da ausência de alguém, lugar ou tempo.",
        example: "Sentir falta de uma pessoa querida distante.",
        question: "O que esse afeto revela sobre o que é valioso para você?",
        synonyms: ["nostalgia", "lembrança terna", "anseio"],
      },
    ],
  },
  {
    id: "raiva",
    name: "Raiva",
    description:
      "Energia de proteção, delimitação de fronteiras e inconformismo.",
    colorToken: "#96551F",
    nuances: [
      {
        id: "irritacao",
        familyId: "raiva",
        label: "Irritação",
        description: "Uma palavra que pode nomear incômodos que se acumulam.",
        example: "Quando pequenos detalhes diários geram tensão e impaciência.",
        question: "O que você percebe ao usar essa palavra?",
        synonyms: ["aborrecimento", "impaciência", "crispação", "chateação"],
      },
      {
        id: "frustracao",
        familyId: "raiva",
        label: "Frustração",
        description: "A distância entre a expectativa e o que de fato ocorreu.",
        example: "Planos que mudam de última hora.",
        question: "Qual expectativa precisa ser reavaliada ou lamentada?",
        synonyms: ["contrariedade", "desapontamento", "impotência"],
      },
      {
        id: "ressentimento",
        familyId: "raiva",
        label: "Ressentimento",
        description: "Eco prolongado de uma situação percebida como injusta.",
        example: "Relembrar uma fala que feriu limites pessoais.",
        question: "Qual limite pessoal pede clareza ou expressão?",
        synonyms: ["amargura", "indignação", "mágoa guardada"],
      },
    ],
  },
  {
    id: "medo",
    name: "Medo",
    description:
      "Sinalização de vulnerabilidade, risco ou necessidade de preparo.",
    colorToken: "#4B4B49",
    nuances: [
      {
        id: "apreensao",
        familyId: "medo",
        label: "Apreensão",
        description: "Expectativa tensa em relação ao que ainda vai acontecer.",
        example: "Aguardar um resultado importante ou uma conversa difícil.",
        question: "O que na situação atual parece incerto ou ameaçador?",
        synonyms: ["ansiedade leve", "preocupação", "expectativa tensa"],
      },
      {
        id: "receio",
        familyId: "medo",
        label: "Receio",
        description: "Cautela diante de um cenário desconhecido.",
        example: "Entrar em um ambiente novo pela primeira vez.",
        question: "De que apoio você precisaria para se sentir mais seguro?",
        synonyms: ["cautela", "timidez", "escrúpulo"],
      },
      {
        id: "inseguranca",
        familyId: "medo",
        label: "Insegurança",
        description: "Dúvida sobre a própria capacidade de sustentação.",
        example: "Sentir que não domina o assunto exigido.",
        question: "Onde você pode encontrar firmeza dentro de si?",
        synonyms: ["fragilidade", "incerteza", "desamparo"],
      },
    ],
  },
  {
    id: "surpresa",
    name: "Surpresa",
    description: "Desorientação momentânea e abertura ao inesperado.",
    colorToken: "#FED701",
    nuances: [
      {
        id: "espanto",
        familyId: "surpresa",
        label: "Espanto",
        description: "Reação súbita diante de algo totalmente fora do script.",
        example: "Ver algo acontecer de forma completamente imprevista.",
        question: "Como seu corpo reagiu a essa quebra de expectativa?",
        synonyms: ["chocante", "sobressalto", "surpresa súbita"],
      },
      {
        id: "admiracao",
        familyId: "surpresa",
        label: "Admiração",
        description: "Assombro agradável diante de algo belo ou grandioso.",
        example: "Contemplar uma paisagem natural impressionante.",
        question: "O que esse vislumbre desperta em sua sensibilidade?",
        synonyms: ["fascínio", "maravilhamento", "estupor positivo"],
      },
      {
        id: "perplexidade",
        familyId: "surpresa",
        label: "Perplexidade",
        description: "Paralisação curiosa tentando compreender o inusitado.",
        example: "Oir uma informação que desafia suas premissas.",
        question: "O que você precisa absorver antes de tirar conclusões?",
        synonyms: ["confusão leve", "incerteza curiosa", "atônito"],
      },
    ],
  },
  {
    id: "aversao",
    name: "Aversão",
    description:
      "Afetação de repulsa ou recusa diante do que fere ou incomoda.",
    colorToken: "#FE538B",
    nuances: [
      {
        id: "repulsa",
        familyId: "aversao",
        label: "Repulsa",
        description:
          "Rejeição visceral a algo considerado tóxico ou impróprio.",
        example: "Distanciar-se de comportamentos ou ambientes nocivos.",
        question: "O que essa rejeição está protegendo em você?",
        synonyms: ["asco", "nojo", "repugnância"],
      },
      {
        id: "incomodo",
        familyId: "aversao",
        label: "Incômodo",
        description: "Divergência sutil ou atrito com o ambiente ou discurso.",
        example: "Ouvir um comentário que soa falso ou invasivo.",
        question: "Qual valor seu foi tocado por essa situação?",
        synonyms: ["desconforto", "atrito", "desacordo sutil"],
      },
      {
        id: "rejeicao",
        familyId: "aversao",
        label: "Rejeição",
        description:
          "Decisão consciente de não aceitar ou não pactuar com algo.",
        example: "Dizer não a uma demanda que ultrapassa seu limite.",
        question: "Como é sustentar esse 'não' para si mesmo?",
        synonyms: ["recusa", "negação", "afastamento"],
      },
    ],
  },
];
