/**
 * Catálogo Editorial Versionado de Necessidades - Instituto Figura Viva
 * Registro Confluência
 */
import { CatalogVersion } from './types';

export const INITIAL_CATALOG_VERSION: CatalogVersion = {
  version: '1.0.0',
  publishedAt: '2026-09-01T10:00:00Z',
  publishedBy: 'Coordenação Pedagógica Instituto Figura Viva',
  status: 'published',
  editorialIntro: {
    title: 'Do que você sente necessidade agora?',
    subtitle: 'Dê lugar ao que parece mais presente neste momento.',
    supportText: 'Escolha o que faz sentido. Você não precisa ter certeza nem resolver tudo hoje.',
    estimatedTime: '2–4 min',
  },
  items: [
    {
      id: 'descanso',
      name: 'Descanso',
      shortDescription: 'Tempo para interromper ou diminuir o ritmo.',
      reflectionQuestion: 'O que pede uma pausa ou diminuição no seu ritmo neste momento?',
      gestureExample: 'Separar alguns minutos sem nenhuma tarefa imediata.',
      category: 'ritmo',
      iconName: 'Moon',
      active: true,
      orderIndex: 0,
    },
    {
      id: 'conexao',
      name: 'Conexão',
      shortDescription: 'Estar em contato sincero com alguém.',
      reflectionQuestion: 'Que tipo de presença ou conversa traria conforto e acolhimento agora?',
      gestureExample: 'Enviar uma mensagem simples de escuta ou afeto para alguém de confiança.',
      category: 'relacao',
      iconName: 'Users',
      active: true,
      orderIndex: 1,
    },
    {
      id: 'seguranca',
      name: 'Segurança',
      shortDescription: 'Perceber condições de proteção e previsibilidade.',
      reflectionQuestion: 'O que pode trazer uma sensação de chão firme ou estabilidade hoje?',
      gestureExample: 'Reconhecer apoios concretos ao seu redor e respirar com os pés no chão.',
      category: 'cuidado',
      iconName: 'Shield',
      active: true,
      orderIndex: 2,
    },
    {
      id: 'autonomia',
      name: 'Autonomia',
      shortDescription: 'Ter espaço para escolher seus próprios passos.',
      reflectionQuestion: 'Onde você sente que precisa de liberdade e espaço para decidir?',
      gestureExample: 'Tomar uma pequena decisão diária respeitando o seu próprio tempo.',
      category: 'espaco',
      iconName: 'Compass',
      active: true,
      orderIndex: 3,
    },
    {
      id: 'expressao',
      name: 'Expressão',
      shortDescription: 'Dar forma ao que quer dizer ou manifestar.',
      reflectionQuestion: 'Há algo interno pedindo para ser dito, escrito, desenhado ou compartilhado?',
      gestureExample: 'Anotar em palavras soltas ou rabiscar o que está sentindo, sem filtro.',
      category: 'expressao',
      iconName: 'Feather',
      active: true,
      orderIndex: 4,
    },
    {
      id: 'apoio',
      name: 'Apoio',
      shortDescription: 'Contar com ajuda e não carregar tudo só.',
      reflectionQuestion: 'Quem ou o que poderia tornar esse momento menos pesado?',
      gestureExample: 'Nomear uma tarefa e pedir ajuda a alguém próximo.',
      category: 'cuidado',
      iconName: 'HeartHandshake',
      active: true,
      orderIndex: 5,
    },
    {
      id: 'privacidade',
      name: 'Privacidade',
      shortDescription: 'Ter um espaço reservado e só seu.',
      reflectionQuestion: 'O que você precisa resguardar ou silenciar por um instante?',
      gestureExample: 'Ficar em silêncio por alguns minutos fechando a porta ou os olhos.',
      category: 'espaco',
      iconName: 'Key',
      active: true,
      orderIndex: 6,
    },
    {
      id: 'clareza',
      name: 'Clareza',
      shortDescription: 'Compreender melhor uma situação ou sentimento.',
      reflectionQuestion: 'Que informação, contexto ou perspectiva está faltando para você?',
      gestureExample: 'Dar um passo atrás e esperar o calor do momento assentar antes de concluir.',
      category: 'compreensao',
      iconName: 'Eye',
      active: true,
      orderIndex: 7,
    },
  ],
};
